### PR TITLE
Extendable LoggerNode att data structure

### PR DESCRIPTION
**Pull request by vsevel**
backport https://github.com/dmlloyd/jboss-logmanager-embedded/pull/5 on 1.0.x

### CODE REVIEW

**Comment by vsevel** [comment]
cc @dmlloyd

**Comment by vsevel** [comment]
hello @dmlloyd anything preventing from merging this?

**Review by dmlloyd — APPROVED** [review]
Sorry I lost track of this one. It looks fine.

**Comment by vsevel** [comment]
ok. np. thanks. are you releasing as well?

**Comment by vsevel** [comment]
hi @dmlloyd any chance we can have a `1.0.11` soon? thanks

**Comment by dmlloyd** [comment]
Sure, I can do that today.

**Comment by dmlloyd** [comment]
The release is done, but it will take up to 24 hours to propagate to Maven Central.

**Pull request merged**
